[package]
name = "buri"
version = "0.2.0"
authors = ["meganehouser <sleepy.st818@gmail.com>"]

[dependencies]
toml = "0.2"
rustc-serialize = "0.3"

[dependencies.clap]
version = "2.19"
default-features = false
